# Generated by Django 3.0 on 2019-12-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191224_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='imagesofmodel/'),
        ),
    ]
