# Generated by Django 3.0 on 2019-12-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tiltle',
            new_name='title',
        ),
    ]
